<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="test01"
    errors="1" failures="0" hostname="" id="" package="test01" skipped="0"
    tests="1" time="0.009000" timestamp="Fri, 19 Jan 2018 23:39:17 GMT">
  
    <testcase name="Test01" classname="test01" time="0.009000" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Test01 / Test01]:

  ReferenceError: main is not defined
    at Object.Test01 (C:\Users\nopassword\Desktop\SweatWorks\js-web\tests\test01.js:20:6)
    at Module.call (C:\Users\nopassword\Desktop\SweatWorks\js-web\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\nopassword\Desktop\SweatWorks\js-web\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\nopassword\Desktop\SweatWorks\js-web\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\nopassword\Desktop\SweatWorks\js-web\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\nopassword\Desktop\SweatWorks\js-web\node_modules\q\q.js:796:13)
    at C:\Users\nopassword\Desktop\SweatWorks\js-web\node_modules\q\q.js:556:49
    at runSingle (C:\Users\nopassword\Desktop\SweatWorks\js-web\node_modules\q\q.js:137:13)
    at flush (C:\Users\nopassword\Desktop\SweatWorks\js-web\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    </system-err>
  

  
  </testsuite>
</testsuites>
